### ISSUE TITLE
what tool you are used to generate the path code, is PaintCode?

### ISSUE THREAD

**Issue by nonstriater** [d-ronnqvist/blogpost-codesample-PullToRefresh#2]

**Comment by d-ronnqvist** [comment]
In my answer to [the other issue](https://github.com/d-ronnqvist/blogpost-codesample-PullToRefresh/issues/1) I showed the full process of making the path. I chose to edit the path in [Sketch](http://bohemiancoding.com/sketch/) because it's a vector graphics tool that I'm very comfortable with.
